### ISSUE TITLE
Is there some infomation about struct bpf_insn

### ISSUE THREAD

**Issue by tengliu0929** [xdp-project/bpf-examples#106]
I wonder how to write a bpf instruction or a bpf instruction array, but I search some information by google, can't find any valid infomation, could any one give me a tip or some help. Thank you

**Comment by vincentmli** [comment]
here is a youtube on writing bpf instruction by hand [How to write eBPF byte code by hand](https://youtu.be/Z6Bhhjpj1w4?si=-c_E1xSmwDw3U_eB), but writing bpf instruction by hand  seems to be discouraged by the eBPF maintainer

**Comment by tengliu0929** [comment]
Maybe this could help, thank you
