### ISSUE TITLE
sync some xdp-tools/lib /util to bpf-examples ?

### ISSUE THREAD

**Issue by vincentmli** [xdp-project/bpf-examples#108]
Hi @tohojo 

I am thinking about porting  [XDP DNS ](https://github.com/NLnetLabs/XDPeriments/tree/master/Cookies) which uses bpf tail call to bpf-examples repo with libxdp as example, I think I might need to borrow some code from xdp-tools/lib/util for user space, does that sound good idea to you?

**Comment by tohojo** [comment]
Vincent Li ***@***.***> writes:

> Hi @tohojo 
>
> I am thinking about porting  [XDP DNS
> ](https://github.com/NLnetLabs/XDPeriments/tree/master/Cookies) which
> uses bpf tail call to bpf-examples repo with libxdp as example, I
> think I might need to borrow some code from xdp-tools/lib/util for
> user space, does that sound good idea to you?

Sure, it's no problem to import some of the code from xdp-tools/lib/util
into this repo as well. The only concern is to make sure any bug fixes
get pushed back the other way as needed, but I'm sure that is manageable.
