### ISSUE TITLE
update libbpf ?

### ISSUE THREAD

**Issue by vincentmli** [xdp-project/bpf-examples#113]
Hi @tohojo 

Is it possible to update the libbpf in bpf-examples repo, I want to use bpf_ksym_exists helper that does not exist in the libbpf in the repo, I could send a PR to update the libbpf in this repo if you let me know how to do it :)

**Comment by tohojo** [comment]
Vincent Li ***@***.***> writes:

> Hi @tohojo 
>
> Is it possible to update the libbpf in bpf-examples repo, I want to
> use bpf_ksym_exists helper that does not exist in the libbpf in the
> repo, I could send a PR to update the libbpf in this repo if you let
> me know how to do it :)

Sure, go ahead! You just do a 'git fetch' inside the subdirectory and
then checkout whichever revision you want to update to (best to pick a
tagged revision). Then change back to the bpf-examples top directory and
'git add' the libbpf subdirectory, and then finally commit that change.

**Comment by vincentmli** [comment]
sorry I have not done this before, so bare with me, here is what I did:

```

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples# git branch
* master
  vli-dev
  vli-dnsrrl
  vli-skel
  xdp-synproxy

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples# git fetch upstream

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples# git rebase upstream/master
Current branch master is up to date.

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples# cd lib/libbpf/


root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples/lib/libbpf# git fetch

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples/lib/libbpf# git tag
v0.0.3
v0.0.4
v0.0.5
v0.0.6
v0.0.7
v0.0.8
v0.0.9
v0.1.0
v0.1.1
v0.2
v0.3
v0.4.0
v0.5.0
v0.6.0
v0.6.1
v0.7.0
v0.8.0
v0.8.1
v1.0.0
v1.0.1

```
it looks `git fetch` did not fetch new libbpf version as  the `git tag` output. 

I also looked online on how to update git submodule, for some reason I could not get the submodule libbpf updated at all, I must be miss something :)

**Comment by simosund** [comment]
I think the problem is that the submodule is [xdp-project/libbpf](https://github.com/xdp-project/libbpf), rather than [libbpf/libbpf](https://github.com/libbpf/libbpf), and xdp-project/libbpf has itself has not been updated past v1.01. So to update the libbpf submodule beyond 1.01 the xdp-project/libbpf repository first has to be updated as well. So guess you can either make a PR in the xdp-project/libbpf repository which pulls a later version of upstream libbpf, or maybe just let @tohojo update that. Once that is done you can then go ahead and update the submodule here.

**Comment by tohojo** [comment]
Simon Sundberg ***@***.***> writes:

> I think the problem is that the submodule is
> [xdp-project/libbpf](https://github.com/xdp-project/libbpf), rather
> than [libbpf/libbpf](https://github.com/libbpf/libbpf), and
> xdp-project/libbpf has itself has not been updated past v1.01.

Yup, quite right. Should be updated now :)

**Comment by vincentmli** [comment]
ok, here is what I did, hope I did not do something silly :)

```
root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples/lib/libbpf# git branch
* (HEAD detached at a6d7530)
  master

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples/lib/libbpf# git fetch
remote: Enumerating objects: 771, done.
remote: Counting objects: 100% (712/712), done.
remote: Compressing objects: 100% (217/217), done.
remote: Total 771 (delta 474), reused 582 (delta 437), pack-reused 59
Receiving objects: 100% (771/771), 1.27 MiB | 6.79 MiB/s, done.
Resolving deltas: 100% (509/509), completed with 20 local objects.
From https://github.com/xdp-project/libbpf
   5fc0677..3b09738  master     -> origin/master
 * [new tag]         v1.1.0     -> v1.1.0
 * [new tag]         v1.2.0     -> v1.2.0
 * [new tag]         v1.3.0     -> v1.3.0

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples/lib/libbpf# git tag
v0.0.3
v0.0.4
v0.0.5
v0.0.6
v0.0.7
v0.0.8
v0.0.9
v0.1.0
v0.1.1
v0.2
v0.3
v0.4.0
v0.5.0
v0.6.0
v0.6.1
v0.7.0
v0.8.0
v0.8.1
v1.0.0
v1.0.1
v1.1.0
v1.2.0
v1.3.0

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples/lib/libbpf# git checkout -b v1.3.0 v1.3.0
Previous HEAD position was a6d7530 Makefile: bump version to v1.0.1
Switched to a new branch 'v1.3.0'

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples/lib/libbpf# git branch
  master
* v1.3.0

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples/lib/libbpf# cd ..

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples/lib# cd ..

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples# git branch
* libbpf-update
  master

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples# git add lib/libbpf

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples# git commit -a
[libbpf-update 37aa07e] update libbpf to v1.3.0
 1 file changed, 1 insertion(+), 1 deletion(-)

root@r220:/home/vincent/go/src/github.com/vincentmli/bpf-examples# git push origin libbpf-update

```
