### ISSUE TITLE
./configure is not working on CentOS Stream 9

### ISSUE THREAD

**Issue by skotur-brcm** [xdp-project/bpf-examples#116]
I seem to get this error 
#bpf-examples/./configure
clang: 19.0.0git (https://github.com/llvm/llvm-project.git d4569d42b5cb8ba076f0115d3d21d89f68e6ce9d)
libmnl support: missing - this is required

I tried to check /install libmnl on my setup using 'yum install' , but that seems to suggest that my setup already has it.
[root@dhcp-10-123-154-201 bpf-examples]# yum install -y libmnl
Last metadata expiration check: 0:34:36 ago on Tuesday 12 March 2024 02:33:45 PM.
Package libmnl-1.0.4-15.el9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

bpf-examples]# pkg-config --version
1.7.3

I have got this **working on another setup** where pkg-config --version = 1.4.2 

Think the pkg-config version matters or is the problem here ? Though this is what came with the distro install, did not do anything special/specific for pkg-config

Could you please help get past this ?

Thanks

**Comment by skotur-brcm** [comment]
OKAY thank you so much ...that and a couple of other dependencies like libpcap-devel and glibc-devel.i686 eventually helped me build the AF_XDP example app

**Comment by tohojo** [comment]
skbrcm ***@***.***> writes:

> OKAY thank you so much ...that and a couple of other dependencies like
> libpcap-devel and glibc-devel.i686 eventually helped me build the
> AF_XDP example app

Awesome! You're welcome! :)
