### ISSUE TITLE
Can a Single UMEM be Bound to Multiple Non-Overlapping FQ and CQ Sets Within a Single Process ?

### ISSUE THREAD

**Issue by jklop123** [xdp-project/bpf-examples#120]
Thanks for the excellent resources on XDP provided by the open-source community.

I have a question regarding the use of UMEM in AF_XDP, which might seem basic:

Can a single UMEM in a process only be bound to one set of FQ and CQ? 
- Is it feasible to partition a UMEM into multiple segments, each bound to a distinct set of FQ and CQ, and each set linked to a different XSK? Would this approach help avoid synchronization issues with FQ and CQ in a multi-threaded environment?

This question arose while I was reading the [AF_XDP documentation](https://www.kernel.org/doc/html/latest/networking/af_xdp.html):
- The document mentions two scenarios of UMEM sharing. One scenario involves multiple XSKs in the same process sharing a single UMEM and a pair of FQ/CQ, which requires handling the synchronization of FQ and CQ within the process.

Considering a similar setup, I'm thinking about:
- Setting the network interface's RSS to 1 to simplify the process.
- Calculating a hash for each packet in XDP and directing packets to the appropriate XSK based on this hash.
- If UMEM could support binding to multiple non-overlapping sets of FQ and CQ, it seems it would completely eliminate the need for synchronization.

I appreciate your insights and advice on this matter. Thank you!

**Comment by magnus-karlsson** [comment]
Sorry, but that scenario is not supported at this point in time. If you instead use RSS in the NIC to distribute the packets between queues, then you can use the second mode of XPD_SHARED_UMEM as described in the documentation and this mode will provide you with separate FQs and CQs.

**Comment by jklop123** [comment]
Thank you for your reply. 
In fact, what I want to achieve is: Multi -threaded the original package of L2, which has completely controlled the process of dividing a packet to that thread. The RSS of the network card obviously cannot achieve this process.
Obviously, I can only share one UMEM and a set of FQ CQ based on multiple XKS. Perhaps locking fq CQ and then copying the original package as soon as possible. It is a choice.
