### ISSUE TITLE
Encap IPv6 with ETH_P_IP?

### ISSUE THREAD

**Issue by PolynomialDivision** [xdp-project/bpf-examples#2]
Sry, why do u set `ehdr->h_proto = bpf_htons(ETH_P_IP);`?
https://github.com/xdp-project/bpf-examples/blob/master/encap-forward/xdp_encap.c#L39

If I have IPv6 I would suspect `ehdr->h_proto = bpf_htons(ETH_P_IPV6);`?

**Comment by tohojo** [comment]
Polynomdivision <notifications@github.com> writes:

> Sry, why do u set `ehdr->h_proto = bpf_htons(ETH_P_IP);`?
> https://github.com/xdp-project/bpf-examples/blob/master/encap-forward/xdp_encap.c#L39
>
> If I have IPv6 I would suspect `ehdr->h_proto =
> bpf_htons(ETH_P_IPV6);`?

Yeah, you're right; did most of the testing with IPv4 (and TC) :)
