### ISSUE TITLE
tc_bpf_encap: fails to compile

### ISSUE THREAD

**Issue by PolynomialDivision** [xdp-project/bpf-examples#3]
If I want to compile, it fails with
```c
tc_bpf_encap.c:61:26: error: variable has incomplete type 'struct bpf_redir_neigh'
                struct bpf_redir_neigh nh_params = {};
```

**Comment by tohojo** [comment]
Polynomdivision <notifications@github.com> writes:

> If I want to compile, it fails with
> ```c
> tc_bpf_encap.c:61:26: error: variable has incomplete type 'struct bpf_redir_neigh'
>                 struct bpf_redir_neigh nh_params = {};
> ```

Ah, right, that needs some new kernel headers; let me fix that...

**Comment by PolynomialDivision** [comment]
Wow, awesome support!!! :D
Thanks, for all the tips and suggestions!

**Comment by tohojo** [comment]
Polynomdivision <notifications@github.com> writes:

> Wow, awesome support!!! :D
> Thanks, for all the tips and suggestions!

You're welcome :)
