### ISSUE TITLE
ELF support missing

### ISSUE THREAD

**Issue by effeeue** [xdp-project/bpf-examples#58]
git clone --recurse-submodules https://github.com/xdp-project/bpf-examples
cd bpf-examples/preserve-dscp
make

make[1]: Entering directory '/etc/wireguard/bpf-examples'
sh configure
clang: 11.0.1-2
libbpf support: submodule
ELF support: missing - this is required
make[1]: *** [Makefile:52: config.mk] Error 1
make[1]: Leaving directory '/etc/wireguard/bpf-examples'
../lib/defines.mk:4: ../lib/../config.mk: No such file or directory
make: *** [../lib/common.mk:69: ../lib/../config.mk] Error 2

I'm not sure how to resolve this.

**Comment by effeeue** [comment]
Thank you for your help. That fixed my problem and then led to more problems. However; I was able to resolve those with google. Thanks again.

**Comment by tohojo** [comment]
Great! You're welcome :)
