### ISSUE TITLE
pping: issues with LLVM-15

### ISSUE THREAD

**Issue by hundredmiles** [xdp-project/bpf-examples#63]
First of all, it would be of immense help if the steps to execute an application is mentioned in detail (at least the step by step commands). This saves a lot of time for people who are starting out with eBPF. 

The steps I am following are mentioned below one by one.

```git clone https://github.com/xdp-project/bpf-examples.git```
```./configure```
```make``` gives me error from both the root directory ```bpf-examples``` or from ```pping```

To overcome the error, I have to go ```/lib/xdp-tools``` and then run ```./configure``` followed by ```make```
Next, I again run ```make``` from the root directory ```bpf-examples```. Although errors due to ```libxdp.c``` are not generated, yet error is generated due to ```net64-bpf``` application
```
nat64-bpf
    CLANG    nat64_kern.o
    LLC      nat64_kern.o
    GEN      nat64_kern.skel.h
libbpf: elf: skipping unrecognized data section(9) .rodata.str1.1
    CC       nat64
nat64.c:20:10: fatal error: libmnl/libmnl.h: No such file or directory
   20 | #include <libmnl/libmnl.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

Then all the other applications are commented out except ```pping``` in the ```Makefile``` of the root directory. ```make``` is run again from the root and compilation is successful.

Next, running ```pping``` for TC gives the following error:
```
sudo ./pping -i lo -F json -I tc
Starting ePPing in json mode tracking TCP on lo
libbpf: prog 'tsmap_cleanup': BPF program load failed: Permission denied
libbpf: prog 'tsmap_cleanup': -- BEGIN PROG LOAD LOG --
R1 type=ctx expected=fp
; int tsmap_cleanup(struct bpf_iter__bpf_map_elem *ctx)
0: (bf) r8 = r1
; __u64 *timestamp = ctx->value;
1: (79) r9 = *(u64 *)(r8 +24)
; struct packet_id *pid = ctx->key;
2: (79) r6 = *(u64 *)(r8 +16)
; __u64 now = bpf_ktime_get_ns();
3: (85) call bpf_ktime_get_ns#5
4: (bf) r7 = r0
; debug_update_mapclean_stats(ctx, &events, !ctx->key || !ctx->value,
5: (79) r1 = *(u64 *)(r8 +16)
; debug_update_mapclean_stats(ctx, &events, !ctx->key || !ctx->value,
6: (55) if r1 != 0x0 goto pc+3
 R0_w=invP(id=3) R1_w=invP0 R6_w=rdonly_buf_or_null(id=2,off=0,imm=0) R7_w=invP(id=3) R8_w=ctx(id=0,off=0,imm=0) R9_w=buf_or_null(id=1,off=0,imm=0) R10=fp0
; ctx->meta->seq_num, now,
7: (79) r1 = *(u64 *)(r8 +0)
func 'bpf_iter_bpf_map_elem' arg0 has btf_id 30838 type STRUCT 'bpf_iter_meta'
; ctx->meta->seq_num, now,
8: (79) r1 = *(u64 *)(r1 +16)
9: (05) goto pc+4
; if (map_stats->start_time) { // Non-empty map
14: (18) r2 = 0xffffb359c01a2010
.
.  // Other statements not included
.
164: (bf) r1 = r8
165: (07) r1 += 72
R1 pointer arithmetic on map_value_or_null prohibited, null-check it first
processed 254 insns (limit 1000000) max_states_per_insn 0 total_states 19 peak_states 19 mark_read 10
-- END PROG LOAD LOG --
libbpf: failed to load program 'tsmap_cleanup'
libbpf: failed to load object 'pping_kern.o'
Failed loading bpf programs in pping_kern.o: Permission denied
Failed loading and attaching BPF programs in pping_kern.o
```

Platform: Ubuntu 20.04.5 LTS; 
Kernel: 5.15.0-52-generic

Any help is really appreciated.

**Comment by simosund** [comment]
Hi,
Thanks for reporting this issue. The general repository setup and the `nat64-bpf` issue I'll leave to @netoptimizer  and @tohojo. 

I'll have a look at the `pping` related issue later today to see if I can replicate it and figure out how to solve it. Could you tell me which clang/LLVM version you used to compile the program (may potentially be of relevance)?

**Comment by hundredmiles** [comment]
Hi,

I am using clang-15 and llc-15 (I need to modify the ```cnfigure``` files in the root and ```xdp-tools``` explicitly)

**Comment by simosund** [comment]
Unfortunately I got stuck on another task a bit longer than anticipated, so will have to circle back to this tomorrow (I'm in the CET timezone). 

Based on the steps you've posted, I don't think there should be any additional steps to get `pping` running. It should generally be enough to clone the repository, run `./configure` in the root directory (and install any missing dependencies if it hints at any), and then either run `make` in the root directory to compile all the programs or just `cd` into the directory you're intrested in (in this case `pping`) and run `make` in that directory to only compile that specific example. 

Once you've managed to compile `pping` (which you seem to have managed despite the issues) it should be possible to run it as you did, with ex. `sudo ./pping -i <interface> -I tc <additional args>`. That should cause `pping` to set up the BPF programs (which in your case failed the verifier in the kernel and therefore got rejected, I'll have to investigate why) and then report any RTTs directly to stdout. I should note that regardless of output format (`-F standard/ppviz/json`) `pping` will simply print to stdout right now. The JSON-format does not pretty-print, so you probably want to redirect that output to some file which you can read later. `pping` will then simply continue running until it's interrrupted (Ctrl + C) or killed (sigterm), and which point it will simply do some cleanup and then terminate.

**Comment by hundredmiles** [comment]
No problem :) 

After cloning the repo and ```./configure``` from the root, if I run ```make``` from the root or from the directory of interest (in this case ```pping```), I get lots of error related to the file ```libxdp.c```. After running ```./configure```, the directories ```libbpf``` and ```libxdp``` pulls the necessary files and yet the error occurs. Could you please tell if this a part of the installation of the missing dependencies that you mentioned or it has to do with configuration of the complete repo?

Here is small snippet of the error. 

```
anindya@ubuntu:testebpf/pping$ make
  libbpf
    CC       install/lib/libbpf.a
    INSTALL  install/lib/libbpf.a

  libxdp
    CC       install/lib/libxdp.a
libxdp.c:243:20: error: static declaration of ‘btf__load_from_kernel_by_id’ follows non-static declaration
  243 | static struct btf *btf__load_from_kernel_by_id(__u32 id)
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from libxdp.c:29:
/home/anindya/testebpf/lib/install/include/bpf/btf.h:121:24: note: previous declaration of ‘btf__load_from_kernel_by_id’ was here
  121 | LIBBPF_API struct btf *btf__load_from_kernel_by_id(__u32 id);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
libxdp.c: In function ‘btf__load_from_kernel_by_id’:
libxdp.c:248:2: error: ‘btf__get_from_id’ is deprecated: libbpf v0.6+: use btf__load_from_kernel_by_id instead [-Werror=deprecated-declarations]
  248 |  err = btf__get_from_id(id, &btf);
      |  ^~~
In file included from libxdp.c:29:
/home/anindya/testebpf/lib/install/include/bpf/btf.h:124:16: note: declared here
  124 | LIBBPF_API int btf__get_from_id(__u32 id, struct btf **btf);
      |                ^~~~~~~~~~~~~~~~
libxdp.c: At top level:
libxdp.c:256:14: error: static declaration of ‘btf__type_cnt’ follows non-static declaration
  256 | static __u32 btf__type_cnt(const struct btf *btf)
      |              ^~~~~~~~~~~~~
In file included from libxdp.c:29:
/home/anindya/testebpf/lib/install/include/bpf/btf.h:137:18: note: previous declaration of ‘btf__type_cnt’ was here
  137 | LIBBPF_API __u32 btf__type_cnt(const struct btf *btf);
      |                  ^~~~~~~~~~~~~
libxdp.c: In function ‘btf__type_cnt’:
libxdp.c:259:2: error: ‘btf__get_nr_types’ is deprecated: libbpf v0.7+: use btf__type_cnt() instead; note that btf__get_nr_types() == btf__type_cnt() - 1 [-Werror=deprecated-declarations]
  259 |  return btf__get_nr_types(btf) + 1;
      |  ^~~~~~
In file included from libxdp.c:29:
/home/anindya/testebpf/lib/install/include/bpf/btf.h:136:18: note: declared here
  136 | LIBBPF_API __u32 btf__get_nr_types(const struct btf *btf);
      |                  ^~~~~~~~~~~~~~~~~
libxdp.c: At top level:
libxdp.c:264:24: error: static declaration of ‘bpf_object__next_map’ follows non-static declaration
  264 | static struct bpf_map *bpf_object__next_map(const struct bpf_object *obj,
      |                        ^~~~~~~~~~~~~~~~~~~~
In file included from libxdp.c:28:
/home/anindya/testebpf/lib/install/include/bpf/libbpf.h:718:1: note: previous declaration of ‘bpf_object__next_map’ was here
  718 | bpf_object__next_map(const struct bpf_object *obj, const struct bpf_map *map);
      | ^~~~~~~~~~~~~~~~~~~~
libxdp.c: In function ‘bpf_object__next_map’:
libxdp.c:267:2: error: ‘bpf_map__next’ is deprecated: libbpf v0.7+: use bpf_object__next_map() instead [-Werror=deprecated-declarations]
  267 |  return bpf_map__next(map, obj);
```
This is solved if I go to ```/lib/xdp-tools``` and run ```./configure``` followed by ```make``` and then come to the ```root``` or ```pping``` and run ```make``` again.


However, after successfully compiling ```pping``` the error ```R1 pointer arithmetic on map_value_or_null prohibited, null-check it first``` remains!

**Comment by simosund** [comment]
I've not been able to replicate your issue regarding `configure` and `libxdp`, but think @netoptimizer and @tohojo know more about the overall repository config/setup process. For me it works simply cloning, running `./configure` in the root directory and then `make`, without having to manually run `./configure` in the sub-projects (`/lib/xdp-tools` specifically). You could try to run `git submodule update --init` after cloning the repository (before running `./configure` and `make`) and see if it works then without you having to manually run `./configure` and `make` in `/lib/xdp-tools`, or alternatively just run `git clone --recurse-submodules` when cloning the project. Either way you seem to have figured out how to solve the issue on your own (by running `./configure` and `make` in `lib/xdp-tools`, but I agree we should add some basic setup instructions so you don't have to do that.

As for the issue with `pping`, I have been able to replicate that. It seems to be an issue when compiling with LLVM-15 (clang-15 and llc-15) specifically (works with LLVM-14 and LLVM-13). So as a temporary fix you should be able to modify the `config.mk` file in the root directory (which is generated by `./configure`) so that it uses LLVM-14 by changing the lines:
```
CLANG:=clang
LLC:=llc
```
to
```
CLANG:=clang-14
LLC:=llc-14
```
(assuming you have `clang-14` and `llc-14` installed) and then compile `pping` again. That should hopefully get `pping` running for you while I figure out why the verifier rejects the program when compiled with LLVM-15 and how to fix it.

**Comment by tohojo** [comment]
No need to edit the script, just pass in the variables as envvars:

`LLC=llc-14 CLANG=clang-14 ./configure`

**Comment by simosund** [comment]
I meant edit the `config.mk` (not the script itself), but of course you could also just run the `configure` script with the those as envvars and it will generate the "correct" (workaround) `config.mk`.

**Comment by hundredmiles** [comment]
Thanks @simosund and @tohojo for the suggestions.

pping is working for both TC and XDP with clang-14 and llc-14!

for XDP:
 ```
$ sudo ./pping -i lo -I xdp
Starting ePPing in standard mode tracking TCP on lo
libbpf: elf: skipping unrecognized data section(7) xdp_metadata
libbpf: elf: skipping unrecognized data section(7) xdp_metadata
libbpf: Kernel error message: Exclusivity flag on, cannot modify
packet_ts: cycle: 1, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
flow_state: cycle: 1, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
packet_ts: cycle: 2, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
flow_state: cycle: 2, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
packet_ts: cycle: 3, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
flow_state: cycle: 3, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
packet_ts: cycle: 4, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
flow_state: cycle: 4, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
```

for TC:
```
$ sudo ./pping -i lo -I tc
[sudo] password for anindya: 
Starting ePPing in standard mode tracking TCP on lo
libbpf: Kernel error message: Exclusivity flag on, cannot modify
packet_ts: cycle: 1, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
flow_state: cycle: 1, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
packet_ts: cycle: 2, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
flow_state: cycle: 2, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
packet_ts: cycle: 3, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
flow_state: cycle: 3, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
packet_ts: cycle: 4, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
flow_state: cycle: 4, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
packet_ts: cycle: 5, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
flow_state: cycle: 5, entries: 0, time: 0, timeout: 0, tot timeout: 0, selfdel: 0, tot selfdel: 0
```

On a sidenote, can we ignore the kernel error message from libbpf?

**Comment by simosund** [comment]
> If you want to be sure that this is indeed the reason this error occurs you could try to start pping in XDP mode (-I tc) on an interface you've verified does not have a clsact qdisc attached before running pping, then that libbpf error should not occur. 

Error on my part there, XDP mode should of course be `-I xdp`. That part is important because in tc mode it will try to attach two tc programs (one on ingress and one on egress), so even if there was no previous `clsact` on the interface the second tc program will give that error as the first tc program will have created a `clsact` already. We could of course add some logic to handle this, but for now we've just kept it simple and learned to live with that error message in the beginning.

**Comment by tohojo** [comment]
Simon Sundberg ***@***.***> writes:

>> If you want to be sure that this is indeed the reason this error
>> occurs you could try to start pping in XDP mode (-I tc) on an
>> interface you've verified does not have a clsact qdisc attached
>> before running pping, then that libbpf error should not occur.
>
> Error on my part there, XDP mode should of course be `-I xdp`. That
> part is important because in tc mode it will try to attach two tc
> programs (one on ingress and one on egress), so even if there was no
> previous `clsact` on the interface the second tc program will give
> that error as the first tc program will have created a `clsact`
> already. We could of course add some logic to handle this, but for now
> we've just kept it simple and learned to live with that error message
> in the beginning.

Yeah, we should probably be smarter about this :)

**Comment by hundredmiles** [comment]
Thanks for all the clarifications @simosund!

Shall we close this issue? My problem is solved for now. 

Or shall we change the issue name to something like this "pping failing with clang-15 and llc-15" and track it? You could choose whichever you find suitable.

**Comment by simosund** [comment]
> Yeah, we should probably be smarter about this :)

@tohojo Do you happen to know if there's a relatively simple way to programmatically check for the existence of a `clsact` qdisc on the interface (without running a bunch of shell commands)? Can probably try to check this up myself, but in general I feel like this is maybe not that high priority on the TODO-list right now. But can be good to have on the list of small fixes to work on whenever I have some time.

**Comment by simosund** [comment]
> Shall we close this issue? My problem is solved for now.
>
> Or shall we change the issue name to something like this "pping failing with clang-15 and llc-15" and track it? You could choose whichever you find suitable.

I think we can keep it open slightly longer. I've identified the issue when compiling with LLVM-15, and have found a fix that is hopefully not too ugly. So will push a PR with that fix soon, and can then reference this issue (and then we can close this issue whenever it's fixed). But changing the name of it to reflect the issue being with LLVM-15 is perhaps not a bad idea.

**Comment by simosund** [comment]
Did you try running `git submodule update --init` after cloning, and help with your configuration issue @hundredmiles? Or did you still have to `configure` and `make` `/lib/xdp-tools`?

Otherwise I guess we still also have an issue with the general setup not working optimally in some environments, that may be good to track as well.

**Comment by hundredmiles** [comment]
> Did you try running git submodule update --init after cloning, and help with your configuration issue @hundredmiles? Or did you still have to configure and make /lib/xdp-tools?

Tried running ```git submodule update --init``` right after cloning the repo but still getting errors related to ```libxdp.c``` like before. Again, running ```./configure``` followed by ```make``` in ```/lib/xdp-tools``` solves this.

> But changing the name of it to reflect the issue being with LLVM-15 is perhaps not a bad idea.

Updating the issue name to "pping: issues with LLVM-15".

> Otherwise I guess we still also have an issue with the general setup not working optimally in some environments, that may be good to track as well.

Shall I open another issue?

**Comment by simosund** [comment]
> Shall I open another issue?

Please do! `bpf-examples` is supposed to make it easy (or easier) to start with BPF, so these types of issues I think should be addressed.
