### ISSUE TITLE
AF_XDP-example: Makefile: missing -lpthread 

### ISSUE THREAD

**Issue by elvinongbl** [xdp-project/bpf-examples#73]
Below compilation issue for AF_XDP-example:
    CC       xdpsock
/usr/bin/ld: /tmp/cczx5Wdi.o: in function `main':
/home/bong5/kit-script/sw-tool/bpf-examples/AF_XDP-example/xdpsock.c:2022: undefined reference to `pthread_create'
/usr/bin/ld: /home/bong5/kit-script/sw-tool/bpf-examples/AF_XDP-example/xdpsock.c:2048: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make: *** [../lib/common.mk:83: xdpsock] Error 1

It is due to missing -lpthread in Makefile.

**Comment by tohojo** [comment]
Thank you for the report; fixed! :)
