### ISSUE TITLE
AF_XDP-forwarding test case fails

### ISSUE THREAD

**Issue by tjcw** [xdp-project/bpf-examples#78]
I am working through the bpf-examples, and for me the AF_XDP-forwarding test case fails .
I have a fresh clone of xdp-project/bpf-examples and have just run the `configure` script and run `make` in the AF_XDP-forwarding directory. When I try to run the test case I get
```
tjcw@tjcw-host:~/workspace3/bpf-examples/AF_XDP-forwarding$ sudo ./xsk_fwd -i veth1 -q 0 -i veth2 -q 0 -c 0
[sudo] password for tjcw: 
Buffer pool created successfully.
Port 0 initialization failed.
tjcw@tjcw-host:~/workspace3/bpf-examples/AF_XDP-forwarding$
```
Am I doing something wrong, or is the test case broken ?

**Comment by tohojo** [comment]
Doesn't work for me on veths either; no idea if it's supposed to. @magnus-karlsson would know, hopefully?

**Comment by magnus-karlsson** [comment]
Seems to be broken. I have never tried it on veth interfaces. Will take a look at it.

**Comment by tjcw** [comment]
When I run it under gdb, I see a bind syscall coming back with errno 95 ( EOPNOTSUPP )

**Comment by tjcw** [comment]
Yes, that allows the test case to run. I have created a PR. (I haven't actually sent any packets over the veths; all I have checked is that the test case starts and initialises)
