### ISSUE TITLE
AF_XDP-forwarding  forward package fail

### ISSUE THREAD

**Issue by xjj210130** [xdp-project/bpf-examples#90]
hi all:
   I do on my machine as following:
   1: git clone https://github.com/xdp-project/bpf-examples.git
   2: ./configure && make
   3: ./xsk_fwd -i eth3 -q 3 -i eth5 -q 5 -c 3  
   4:  ping eht3 from  other machine （xsk_fwd catch the package, but no forward）

+------+--------------+---------------+--------------+---------------+
| Port |   RX packets | RX rate (pps) |   TX packets | TX_rate (pps) |
+------+--------------+---------------+--------------+---------------+
|    0 |           13 |             0 |            0 |             0 |
|    1 |            0 |             0 |            0 |             0 |
+------+--------------+---------------+--------------+---------------+

+------+--------------+---------------+--------------+---------------+
| Port |   RX packets | RX rate (pps) |   TX packets | TX_rate (pps) |
+------+--------------+---------------+--------------+---------------+
|    0 |           13 |             0 |            0 |             0 |
|    1 |            0 |             0 |            0 |             0 |
+------+--------------+---------------+--------------+---------------+

Am I doing something wrong? how to solve this?

If i want to change the the package message, i do this in function swap_mac_addresses, is it right?
Thanks.

**Comment by magnus-karlsson** [comment]
The example uses batching and will only forward packets in bursts of 64. Try sending 64 packets or just delete the condition below in thread_func() so that the contents of the if-statement is always executed: 

                        if (btx->n_pkts == MAX_BURST_TX)

**Comment by xjj210130** [comment]
Thanks
